### ISSUE TITLE
Error installing from pastebin

### ISSUE THREAD

**Issue by AvarisLectros** [Adorable-Catgirl/Zorya-BIOS#1]
Hi, I tried to pastebin run the code provided in install.lua and I get this during install
![Capture](https://user-images.githubusercontent.com/54130443/63657351-6238ec00-c766-11e9-9d00-bef7e6dc3de8.PNG)

**Comment by AvarisLectros** [comment]
I'm using the latest version of OpenComputers (OpenComputers-MC1.12.2-1.7.4.153)

**Comment by lunaboards-dev** [comment]
Aha, I forgot to edit the updater. Thank you!
